config/routes.rb
Rails.application.routes.draw do
  resources :priorities
  resources :classrooms
  resources :streams
  resources :departments
  resources :exams
  get 'library/index'

  resources :dormitories
  resources :subjects
  resources :library_books
  resources :subjects
  get 'users/index'

  resources :students
  resources :teachers
  get 'fees/index'

  resources :disciplines
  resources :events
  resources :pay_fees
  resources :pay_others
  devise_for :users
  resources :tasks
  get 'home/index'
  root 'home#index'

end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
    has_many :streams
    has_many :students
    has_many :teachers
end

app/models/department.rb
class Department < ActiveRecord::Base
end

app/models/discipline.rb
class Discipline < ActiveRecord::Base
end

app/models/dormitory.rb
class Dormitory < ActiveRecord::Base
    has_many :teachers
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/exam.rb
class Exam < ActiveRecord::Base
end

app/models/library_book.rb
class LibraryBook < ActiveRecord::Base
end

app/models/pay_fee.rb
class PayFee < ActiveRecord::Base
end

app/models/pay_other.rb
class PayOther < ActiveRecord::Base
end

app/models/priority.rb
class Priority < ActiveRecord::Base
    belongs_to :task
end

app/models/stream.rb
class Stream < ActiveRecord::Base
  belongs_to :classroom #:through=> :teacher
  has_many :teachers
  has_many :students
end

app/models/student.rb
class Student < ActiveRecord::Base
    has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
    
    belongs_to :classroom
    belongs_to :stream
end

app/models/subject.rb
class Subject < ActiveRecord::Base
    belongs_to :teachers
end

app/models/task.rb
class Task < ActiveRecord::Base
    has_many :priorities
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
    has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
    
    belongs_to :stream
    belongs_to :dormitory
    has_many :subjects
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
   attr_accessor :login
   
    def self.find_first_by_auth_conditions(warden_conditions)
  	  conditions = warden_conditions.dup
  		  if login = conditions.delete(:login)
    		  where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
  		  else
    		  if conditions[:username].nil?
      		  	where(conditions).first
    		  else
      		  	where(username: conditions[:username]).first
    		  end
  		  end
	  end
end

app/controllers/disciplines_controller.rb
class DisciplinesController < ApplicationController
  before_action :set_discipline, only: [:show, :edit, :update, :destroy]

  # GET /disciplines
  # GET /disciplines.json
  def index
    @disciplines = Discipline.all
  end

  # GET /disciplines/1
  # GET /disciplines/1.json
  def show
  end

  # GET /disciplines/new
  def new
    @discipline = Discipline.new
  end

  # GET /disciplines/1/edit
  def edit
  end

  # POST /disciplines
  # POST /disciplines.json
  def create
    @discipline = Discipline.new(discipline_params)

    respond_to do |format|
      if @discipline.save
        format.html { redirect_to @discipline, notice: 'Discipline was successfully created.' }
        format.json { render :show, status: :created, location: @discipline }
      else
        format.html { render :new }
        format.json { render json: @discipline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /disciplines/1
  # PATCH/PUT /disciplines/1.json
  def update
    respond_to do |format|
      if @discipline.update(discipline_params)
        format.html { redirect_to @discipline, notice: 'Discipline was successfully updated.' }
        format.json { render :show, status: :ok, location: @discipline }
      else
        format.html { render :edit }
        format.json { render json: @discipline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /disciplines/1
  # DELETE /disciplines/1.json
  def destroy
    @discipline.destroy
    respond_to do |format|
      format.html { redirect_to disciplines_url, notice: 'Discipline was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discipline
      @discipline = Discipline.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def discipline_params
      params.require(:discipline).permit(:incident, :incident_date, :category, :form, :details, :action_taken, :email_subject, :email_message, :email_address, :references, :student_id)
    end
end

app/helpers/disciplines_helper.rb
module DisciplinesHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/fees_helper.rb
module FeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/disciplines/_form.html.erb
<% title "SchoolSys :: Report an Incident" %> 

<%= form_for(@discipline) do |f| %>
  <% if @discipline.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@discipline.errors.count, "error") %> prohibited this discipline from being saved:</h2>

      <ul>
      <% @discipline.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :incident %><br>
    <%= f.text_field :incident %>
  </div>
  
  <div class="field">
    <%= f.label :category %><br>
    <%= f.select :category, ["One","Two","Other"] %>
  </div>
  
  <div class="field">
    <%= f.label :incident_date %><br>
    <%= f.date_select :incident_date %>
  </div>
  <div class="field">
    <%= f.label :student %><br>
    <%#= f.text_field :student %>
    <%= f.select :student_id, Student.all.map {|s| [s.fullname, s.id]} %>
  </div>
  <div class="field">
    <%= f.label :adm_no %><br>
    <%#= f.number_field :adm_no %>
    <%= f.select :student_id, Student.all.map {|s| [s.adm_no, s.id]} %>
  </div>
  <div class="field">
    <%= f.label :form %><br>
    <%#= f.text_field :form %>
    <%= f.select :student_id, Student.all.map {|s| [s.classroom_id, s.id]} %>
    <%= f.select :student_id, Student.all.map {|s| [s.stream_id, s.id]} %>
  </div>
  <div class="field">
    <%= f.label :details %><br>
    <%= f.text_area :details %>
  </div>
  <div class="field">
    <%= f.label :action_taken %><br>
    <%= f.text_area :action_taken %>
  </div>
  <div class="field">
    <%= f.label :email_subject %><br>
    <%= f.text_field :email_subject %>
  </div>
  <div class="field">
    <%= f.label :email_message %><br>
    <%= f.text_area :email_message %>
  </div>
  <div class="field">
    <%= f.label :email_address %><br>
    <%= f.text_field :email_address %>
  </div>
  <div class="field">
    <%= f.label :references %><br>
    <%#= f.text_field :references %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/disciplines/edit.html.erb
<h1>Editing Discipline</h1>

<%= render 'form' %>

<%= link_to 'Show', @discipline %> |
<%= link_to 'Back', disciplines_path %>

app/views/disciplines/index.html.erb
<% title "SchoolSys :: Discipline Cases" %> <!-- have an analysis chart to document these cases. also track frequent cases/ people who cause the cases  -->

<p id="notice"><%= notice %></p>

<h1>Listing Disciplines</h1>

<table>
  <thead>
    <tr>
      <th>Incident</th>
      <th>Category</th>
      <th>Incident date</th>
      <th>Student</th>
      <th>Adm no</th>
      <th>Form</th>
      <th>Details</th>
      <th>Action taken</th>
      <th>Email subject</th>
      <th>Email message</th>
      <th>Email address</th>
      <th>References</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @disciplines.each do |discipline| %>
      <tr>
        <td><%= discipline.incident %></td>
        <td><%= discipline.category %></td>
        <td><%= discipline.incident_date %></td>
        <td><%= discipline.student %></td>
        <td><%= discipline.adm_no %></td>
        <td><%= discipline.form %></td>
        <td><%= discipline.details %></td>
        <td><%= discipline.action_taken %></td>
        <td><%= discipline.email_subject %></td>
        <td><%= discipline.email_message %></td>
        <td><%= discipline.email_address %></td>
        <!-- still dont remember what references is -->
        <td><%#= discipline.references %></td>
        <td><%= link_to 'Show', discipline %></td>
        <td><%= link_to 'Edit', edit_discipline_path(discipline) %></td>
        <td><%= link_to 'Destroy', discipline, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Discipline', new_discipline_path %>

app/views/disciplines/new.html.erb
<h1>New Discipline</h1>

<%= render 'form' %>

<%= link_to 'Back', disciplines_path %>

app/views/disciplines/show.html.erb
<% title "SchoolSys :: Incident" %> 

<p id="notice"><%= notice %></p>

<p>
  <strong>Incident:</strong>
  <%= @discipline.incident %>
</p>

<p>
  <strong>Category:</strong>
  <%= @discipline.category %>
</p>

<p>
  <strong>Incident date:</strong>
  <%= @discipline.incident_date %>
</p>

<p>
  <strong>Student:</strong>
  <%= @discipline.student %>
</p>

<p>
  <strong>Adm no:</strong>
  <%= @discipline.adm_no %>
</p>

<p>
  <strong>Form:</strong>
  <%= @discipline.form %>
</p>

<p>
  <strong>Details:</strong>
  <%= @discipline.details %>
</p>

<p>
  <strong>Action taken:</strong>
  <%= @discipline.action_taken %>
</p>

<p>
  <strong>Email subject:</strong>
  <%= @discipline.email_subject %>
</p>

<p>
  <strong>Email message:</strong>
  <%= @discipline.email_message %>
</p>

<p>
  <strong>Email address:</strong>
  <%= @discipline.email_address %>
</p>

<p>
  <strong>References:</strong>
  <%#= @discipline.references %>
</p>

<%= link_to 'Edit', edit_discipline_path(@discipline) %> |
<%= link_to 'Back', disciplines_path %>