config/routes.rb
Rails.application.routes.draw do
  resources :priorities
  resources :classrooms
  resources :streams
  resources :departments
  resources :exams
  get 'library/index'

  resources :dormitories
  resources :subjects
  resources :library_books
  resources :subjects
  get 'users/index'

  resources :students
  resources :teachers
  get 'fees/index'

  resources :disciplines
  resources :events
  resources :pay_fees
  resources :pay_others
  devise_for :users
  resources :tasks
  get 'home/index'
  root 'home#index'

end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
    has_many :streams
    has_many :students
    has_many :teachers
end

app/models/department.rb
class Department < ActiveRecord::Base
end

app/models/discipline.rb
class Discipline < ActiveRecord::Base
end

app/models/dormitory.rb
class Dormitory < ActiveRecord::Base
    has_many :teachers
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/exam.rb
class Exam < ActiveRecord::Base
end

app/models/library_book.rb
class LibraryBook < ActiveRecord::Base
end

app/models/pay_fee.rb
class PayFee < ActiveRecord::Base
end

app/models/pay_other.rb
class PayOther < ActiveRecord::Base
end

app/models/priority.rb
class Priority < ActiveRecord::Base
    belongs_to :task
end

app/models/stream.rb
class Stream < ActiveRecord::Base
  belongs_to :classroom #:through=> :teacher
  has_many :teachers
  has_many :students
end

app/models/student.rb
class Student < ActiveRecord::Base
    has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
    
    belongs_to :classroom
    belongs_to :stream
end

app/models/subject.rb
class Subject < ActiveRecord::Base
    belongs_to :teachers
end

app/models/task.rb
class Task < ActiveRecord::Base
    has_many :priorities
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
    has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
    
    belongs_to :stream
    belongs_to :dormitory
    has_many :subjects
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
   attr_accessor :login
   
    def self.find_first_by_auth_conditions(warden_conditions)
  	  conditions = warden_conditions.dup
  		  if login = conditions.delete(:login)
    		  where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
  		  else
    		  if conditions[:username].nil?
      		  	where(conditions).first
    		  else
      		  	where(username: conditions[:username]).first
    		  end
  		  end
	  end
end

app/controllers/streams_controller.rb
class StreamsController < ApplicationController
  before_action :set_stream, only: [:show, :edit, :update, :destroy]

  # GET /streams
  # GET /streams.json
  def index
    @streams = Stream.all
  end

  # GET /streams/1
  # GET /streams/1.json
  def show
  end

  # GET /streams/new
  def new
    @stream = Stream.new
  end

  # GET /streams/1/edit
  def edit
  end

  # POST /streams
  # POST /streams.json
  def create
    @stream = Stream.new(stream_params)

    respond_to do |format|
      if @stream.save
        format.html { redirect_to @stream, notice: 'Stream was successfully created.' }
        format.json { render :show, status: :created, location: @stream }
      else
        format.html { render :new }
        format.json { render json: @stream.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /streams/1
  # PATCH/PUT /streams/1.json
  def update
    respond_to do |format|
      if @stream.update(stream_params)
        format.html { redirect_to @stream, notice: 'Stream was successfully updated.' }
        format.json { render :show, status: :ok, location: @stream }
      else
        format.html { render :edit }
        format.json { render json: @stream.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /streams/1
  # DELETE /streams/1.json
  def destroy
    @stream.destroy
    respond_to do |format|
      format.html { redirect_to streams_url, notice: 'Stream was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stream
      @stream = Stream.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stream_params
      params.require(:stream).permit(:name,:streams_id, :classroom_id, :teacher_id)
    end
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/fees_helper.rb
module FeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/streams_helper.rb
module StreamsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/streams/_form.html.erb
<%= form_for(@stream) do |f| %>
  <% if @stream.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stream.errors.count, "error") %> prohibited this stream from being saved:</h2>

      <ul>
      <% @stream.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
   <div class="field">
    <%= f.label :Class_teacher %><br><!-- select this from teachers. Dont forget to update the controller for this new field-->
    <%= f.select :teacher_id, Teacher.all.map {|t| [t.fullname, t.id]} %>
  </div>
  <div class="field">
    <%= f.label :Form %><br><!-- select this from teachers. Dont forget to update the controller for this new field-->
    <%= f.select :classroom_id, Classroom.all.map {|c| [c.number, c.id]} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/streams/edit.html.erb
<h1>Editing Stream</h1>

<%= render 'form' %>

<%= link_to 'Show', @stream %> |
<%= link_to 'Back', streams_path %>

app/views/streams/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Streams</h1>

<table>
  <thead>
    <tr>
      <th>Class Teacher</th>
       <th>Class</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @streams.each do |stream| %>
      <tr>
        <td><%= stream.teacher.fullname %></td>
        <td><%= stream.classroom.number %></td>
        <td><%= stream.name %></td>
        <td><%= link_to 'Show', stream %></td>
        <td><%= link_to 'Edit', edit_stream_path(stream) %></td>
        <td><%= link_to 'Destroy', stream, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stream', new_stream_path %>

app/views/streams/new.html.erb
<h1>New Stream</h1>

<%= render 'form' %>

<%= link_to 'Back', streams_path %>

app/views/streams/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong></strong>Class:</strong>
  <%= @stream.classroom.number %>
</p>
<p>
  <strong>Name:</strong>
  <%= @stream.name %>
</p>
<p>
  <strong>Teacher:</strong>
  <%= @stream.teacher.fullname %>
</p>

<%= link_to 'Edit', edit_stream_path(@stream) %> |
<%= link_to 'Back', streams_path %>