config/routes.rb
Rails.application.routes.draw do
  resources :priorities
  resources :classrooms
  resources :streams
  resources :departments
  resources :exams
  get 'library/index'

  resources :dormitories
  resources :subjects
  resources :library_books
  resources :subjects
  get 'users/index'

  resources :students
  resources :teachers
  get 'fees/index'

  resources :disciplines
  resources :events
  resources :pay_fees
  resources :pay_others
  devise_for :users
  resources :tasks
  get 'home/index'
  root 'home#index'

end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
    has_many :streams
    has_many :students
    has_many :teachers
end

app/models/department.rb
class Department < ActiveRecord::Base
end

app/models/discipline.rb
class Discipline < ActiveRecord::Base
end

app/models/dormitory.rb
class Dormitory < ActiveRecord::Base
    has_many :teachers
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/exam.rb
class Exam < ActiveRecord::Base
end

app/models/library_book.rb
class LibraryBook < ActiveRecord::Base
end

app/models/pay_fee.rb
class PayFee < ActiveRecord::Base
end

app/models/pay_other.rb
class PayOther < ActiveRecord::Base
end

app/models/priority.rb
class Priority < ActiveRecord::Base
    belongs_to :task
end

app/models/stream.rb
class Stream < ActiveRecord::Base
  belongs_to :classroom #:through=> :teacher
  has_many :teachers
  has_many :students
end

app/models/student.rb
class Student < ActiveRecord::Base
    has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
    
    belongs_to :classroom
    belongs_to :stream
end

app/models/subject.rb
class Subject < ActiveRecord::Base
    belongs_to :teachers
end

app/models/task.rb
class Task < ActiveRecord::Base
    has_many :priorities
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
    has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
    
    belongs_to :stream
    belongs_to :dormitory
    has_many :subjects
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
   attr_accessor :login
   
    def self.find_first_by_auth_conditions(warden_conditions)
  	  conditions = warden_conditions.dup
  		  if login = conditions.delete(:login)
    		  where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
  		  else
    		  if conditions[:username].nil?
      		  	where(conditions).first
    		  else
      		  	where(username: conditions[:username]).first
    		  end
  		  end
	  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:fullname, :gender, :employer, :employee_number, :employment_date, :birthdate, :marital_status, :nationality, :home_address, :phone_1, :phone_2, :email, :town, :county, :education, :certifications, :subjects, :image, :student_id)
    end
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/fees_helper.rb
module FeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/teachers/_form.html.erb
<% title "SchoolSys :: New Teacher" %>

<%= form_for @teacher, url: teachers_path, html: { multipart: true } do |f| %>
  <% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% @teacher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fullname %><br>
    <%= f.text_field :fullname %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%#= f.text_field :gender %>
    <%= f.select :gender, ["Male","Female","Other"] %>
  </div>
  <div class="field">
    <%= f.label :employer %><br>
    <%= f.text_field :employer %>
  </div>
  <div class="field">
    <%= f.label :employee_number %><br>
    <%= f.text_field :employee_number %>
  </div>
  <div class="field">
    <%= f.label :employment_date %><br>
    <%= f.date_select :employment_date %>
  </div>
  <div class="field">
    <%= f.label :birthdate %><br>
    <%= f.date_select :birthdate, :start_year=>1955,:end_year=>2050 %>
    <!-- you are older than my system retire -->
  </div>
  <div class="field">
    <%= f.label :marital_status %><br>
    <%= f.select :marital_status, ["Single","Complicated","Married","Divorced","Separated","Widowed"] %>
  </div>
  <div class="field">
    <%= f.label :nationality %><br>
    <%= f.text_field :nationality %>
    <%#= country_select("teacher", "country") %><!-- to figure out how to call -->
  </div>
  <div class="field">
    <%= f.label :home_address %><br>
    <%= f.text_field :home_address %>
  </div>
  <div class="field">
    <%= f.label :phone_1 %><br>
    <%= f.number_field :phone_1 %>
  </div>
  <div class="field">
    <%= f.label :phone_2 %><br>
    <%= f.number_field :phone_2 %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :town %><br>
    <%= f.text_field :town %>
  </div>
  <div class="field">
    <%= f.label :county %><br>
    <%= f.text_field :county %>
  </div>
  <div class="field">
    <%= f.label :education %><br>
    <%= f.text_area :education %>
  </div>
  <div class="field">
    <%= f.label :certifications %><br>
    <%= f.text_area :certifications %>
  </div>
  <div class="field">
    <%= f.label :subjects %><br>
    <%= f.text_area :subjects %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<h1>Editing Teacher</h1>

<%= render 'form' %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/index.html.erb
<% title "SchoolSys :: Teachers" %>

<p id="notice"><%= notice %></p>

<h1>Listing Teachers</h1>

<table>
  <thead>
    <tr>
      <th>Fullname</th>
      <th>Gender</th>
      <th>Employer</th>
      <th>Employee number</th>
      <th>Employment date</th>
      <th>Birthdate</th>
      <th>Marital status</th>
      <th>Nationality</th>
      <th>Home address</th>
      <th>Phone 1</th>
      <th>Phone 2</th>
      <th>Email</th>
      <th>Town</th>
      <th>County</th>
      <th>Education</th>
      <th>Certifications</th>
      <th>Subjects</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.fullname %></td>
        <td><%= teacher.gender %></td>
        <td><%= teacher.employer %></td>
        <td><%= teacher.employee_number %></td>
        <td><%= teacher.employment_date %></td>
        <td><%= teacher.birthdate %></td>
        <td><%= teacher.marital_status %></td>
        <td><%= teacher.nationality %></td>
        <td><%= teacher.home_address %></td>
        <td><%= teacher.phone_1 %></td>
        <td><%= teacher.phone_2 %></td>
        <td><%= teacher.email %></td>
        <td><%= teacher.town %></td>
        <td><%= teacher.county %></td>
        <td><%= teacher.education %></td>
        <td><%= teacher.certifications %></td>
        <td><%= teacher.subjects %></td>
        <td><%= image_tag teacher.image.url(:thumb) %></td>
        <td><%= link_to 'Show', teacher %></td>
        <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
        <td><%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teacher', new_teacher_path %>

app/views/teachers/new.html.erb
<h1>New Teacher</h1>

<%= render 'form' %>

<%= link_to 'Back', teachers_path %>

app/views/teachers/show.html.erb
<% title "SchoolSys :: Teacher" %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Fullname:</strong>
  <%= @teacher.fullname %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @teacher.gender %>
</p>

<p>
  <strong>Employer:</strong>
  <%= @teacher.employer %>
</p>

<p>
  <strong>Employee number:</strong>
  <%= @teacher.employee_number %>
</p>

<p>
  <strong>Employment date:</strong>
  <%= @teacher.employment_date %>
</p>

<p>
  <strong>Birthdate:</strong>
  <%= @teacher.birthdate %>
</p>

<p>
  <strong>Marital status:</strong>
  <%= @teacher.marital_status %>
</p>

<p>
  <strong>Nationality:</strong>
  <%= @teacher.nationality %>
</p>

<p>
  <strong>Home address:</strong>
  <%= @teacher.home_address %>
</p>

<p>
  <strong>Phone 1:</strong>
  <%= @teacher.phone_1 %>
</p>

<p>
  <strong>Phone 2:</strong>
  <%= @teacher.phone_2 %>
</p>

<p>
  <strong>Email:</strong>
  <%= @teacher.email %>
</p>

<p>
  <strong>Town:</strong>
  <%= @teacher.town %>
</p>

<p>
  <strong>County:</strong>
  <%= @teacher.county %>
</p>

<p>
  <strong>Education:</strong>
  <%= @teacher.education %>
</p>

<p>
  <strong>Certifications:</strong>
  <%= @teacher.certifications %>
</p>

<p>
  <strong>Subjects:</strong>
  <%= @teacher.subjects %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @teacher.image.url(:medium) %>
</p>

<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>